apiVersion: v1
kind: Service
metadata:
 name: matrix-entrypoint
 namespace: default
spec:
 type: NodePort
 selector:
  app: matrix
 ports:
 - port: 60000
   targetPort: 60000
   nodePort: 31010
 externalTrafficPolicy: Cluster